"""Regenerate tests/release_vectors.h: releases signed by tools/release.py, checked by
main/release.c in test_core. Test-only keys, derived from fixed numbers.

    python tests/gen_release_vectors.py tests/release_vectors.h
    python tests/gen_release_vectors.py - --config-only    (print only the config vector)
"""
import os
import sys

from cryptography.hazmat.primitives.asymmetric import ec

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
import release  # noqa: E402

K0 = ec.derive_private_key(0x5EED0001 << 200 | 0xC0FFEE, ec.SECP256R1())
K1 = ec.derive_private_key(0x5EED0002 << 200 | 0xBEEF, ec.SECP256R1())
NODE = bytes.fromhex("30eda0000001")
BOARD = "test-board"
# A node config (main/cfg.h), signed for NODE, for the config slot tests.
CFG_PAYLOAD = (b'{"format":1,"name":"test","network":{"address":"192.0.2.3/24","gateway":"192.0.2.1"},'
               b'"forwarders":["9.9.9.9"],"time":{"tz":"EST5EDT,M3.2.0,M11.1.0"}}')


def arr(name, b):
    body = ",".join(f"0x{x:02x}" for x in b)
    return f"static const uint8_t {name}[{len(b)}] = {{{body}}};"


fw_payload = b"hello firmware"
fw = release.header(K0, "firmware", 0, NODE, BOARD, 1000, fw_payload)
bl_payload = b"blocklist bytes"
bl = release.header(K1, "blocklist", 1, release.ANY_NODE, BOARD, 2000, bl_payload)
m = bytearray(release.manifest("firmware", 0, NODE, BOARD, 1001, fw_payload))
m[100] = 1  # reserved byte set, validly signed
rsv = bytes(m) + release.sign(K0, bytes(m))
cfg_payload = CFG_PAYLOAD
cfg = release.header(K0, "config", 0, NODE, BOARD, 3000, cfg_payload)


def vectors():
    """The lines for the config vector alone (appended to an existing file)."""
    return [arr("V_CFG", cfg), arr("V_CFG_PAYLOAD", cfg_payload)]


out = []
out.append("/* Generated by tests/gen_release_vectors.py. Do not edit. */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append(arr("V_KEY0", release.public_raw(K0)))
out.append(arr("V_KEY1", release.public_raw(K1)))
out.append(arr("V_NODE", NODE))
out.append(f'#define V_BOARD "{BOARD}"')
out.append(arr("V_FW", fw))
out.append(arr("V_FW_PAYLOAD", fw_payload))
out.append(arr("V_BL", bl))
out.append(arr("V_BL_PAYLOAD", bl_payload))
out.append(arr("V_RESERVED", rsv))
out.extend(vectors())

if len(sys.argv) > 2 and sys.argv[2] == "--config-only":
    print("\n".join(vectors()))
    sys.exit(0)
with open(sys.argv[1], "w") as f:
    f.write("\n".join(out) + "\n")
