// blockvectors writes firmware/tests/blocklist_vectors.h: blocklist files built here and
// the answers the controller expects for a set of queries, so the node's C lookup
// (firmware/main/blocklist.c) is tested against this compiler.
//
//	go run ./cmd/blockvectors ../firmware/tests/blocklist_vectors.h
package main

import (
	"fmt"
	"log"
	"math/rand/v2"
	"os"
	"strings"

	"github.com/skitzo2000/espdns/controller/internal/blocklist"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: blockvectors <out.h>")
	}
	r := rand.New(rand.NewPCG(7, 11))
	word := func() string {
		const a = "abcdefghijklmnopqrstuvwxyz0123456789-"
		b := make([]byte, 3+r.IntN(10))
		for i := range b {
			b[i] = a[r.IntN(26)]
		}
		return string(b)
	}
	tlds := []string{"com", "net", "org", "io", "de"}
	name := func(labels int) string {
		p := []string{}
		for range labels - 1 {
			p = append(p, word())
		}
		return strings.Join(append(p, tlds[r.IntN(len(tlds))]), ".")
	}
	var entries []blocklist.Entry
	for range 800 {
		entries = append(entries, blocklist.Entry{Name: name(2 + r.IntN(3)), Suffix: true})
	}
	for range 400 {
		entries = append(entries, blocklist.Entry{Name: name(3 + r.IntN(2))})
	}
	// Allow entries against them, each kind of precedence: an allowed subdomain of a
	// blocked suffix with a blocked name under it again, an allowed exact name under a
	// blocked suffix (its subdomains stay blocked), an allow for the blocked name itself,
	// and allows for names no list blocks.
	var qs []string
	var exa []string
	for _, e := range entries[800:] {
		exa = append(exa, e.Name)
	}
	i := 0
	for _, e := range entries[:800] {
		s := e.Name
		switch i++; i % 6 {
		case 0: // allow suffix a.s, block exact b.a.s
			a := word() + "." + s
			entries = append(entries, blocklist.Entry{Name: a, Suffix: true, Allow: true}, blocklist.Entry{Name: "b." + a})
			qs = append(qs, a, "x."+a, "b."+a, "c.b."+a, word()+"."+s)
		case 1: // allow exact s
			entries = append(entries, blocklist.Entry{Name: s, Allow: true})
			qs = append(qs, s, "www."+s, strings.ToUpper(s)+".")
		case 2: // allow exact www.s
			entries = append(entries, blocklist.Entry{Name: "www." + s, Allow: true})
			qs = append(qs, "www."+s, "a.www."+s, "WWW."+strings.ToUpper(s)+".")
		case 3: // allow suffix s: the block entry is overruled
			entries = append(entries, blocklist.Entry{Name: s, Suffix: true, Allow: true})
			qs = append(qs, s, "m."+s)
		}
	}
	for j, s := range exa {
		if j%5 == 0 { // allow suffix over a blocked exact name, and over its parent
			entries = append(entries, blocklist.Entry{Name: s[strings.IndexByte(s, '.')+1:], Suffix: true, Allow: true})
			qs = append(qs, s, "w."+s)
		}
	}
	for range 60 { // allowed, never blocked
		n := name(2 + r.IntN(3))
		entries = append(entries, blocklist.Entry{Name: n, Suffix: r.IntN(2) == 0, Allow: true})
		qs = append(qs, n, "q."+n)
	}
	c := blocklist.Compile(entries)

	for i, s := range c.Suffix {
		qs = append(qs, s)
		if i%3 == 0 {
			qs = append(qs, word()+"."+word()+"."+s, strings.ToUpper(word()+"."+s))
		}
		if i%5 == 0 {
			qs = append(qs, s[strings.IndexByte(s, '.')+1:]) // a parent: not blocked
		}
	}
	for i, s := range c.Exact {
		qs = append(qs, s)
		if i%3 == 0 {
			qs = append(qs, "www."+s, s[strings.IndexByte(s, '.')+1:])
		}
	}
	for range 1500 {
		qs = append(qs, name(2+r.IntN(4)))
	}
	qs = append(qs, "com", "localhost")

	var kb [16]byte
	for i := range kb {
		kb[i] = byte(0xa0 + i)
	}
	k := blocklist.KeyFromBytes(kb)

	var o strings.Builder
	fmt.Fprintf(&o, "/* Generated by controller/cmd/blockvectors: do not edit. */\n#pragma once\n#include <stdint.h>\n\n")
	fmt.Fprintf(&o, "static const char *const blv_queries[%d] = {\n", len(qs))
	for _, q := range qs {
		fmt.Fprintf(&o, "    %q,\n", q)
	}
	fmt.Fprintf(&o, "};\n\n")

	// The verdicts the compiler means (no hashes), which the 44-bit file must give too.
	meant := c.Verdict()

	// Two files: 44-bit hashes with a filter, and 20-bit hashes without one, which packs
	// sectors densely and makes real collisions, so every decoding path runs.
	for _, v := range []struct {
		id         string
		bits, xorb int
	}{{"f44", 44, 10}, {"f20", 20, 0}} {
		ts := c.Hashes(k, uint(v.bits))
		file, st, err := blocklist.WriteFile(k, v.bits, v.xorb, ts)
		if err != nil {
			log.Fatal(err)
		}
		var count [3]int
		fmt.Fprintf(&o, "/* %d-bit hashes, xor %d: %d bytes; hashes: %d exact, %d suffix, %d allow exact, %d allow suffix */\n",
			v.bits, v.xorb, st.Size, len(ts[0]), len(ts[1]), len(ts[2]), len(ts[3]))
		fmt.Fprintf(&o, "static const uint8_t blv_%s_file[%d] __attribute__((aligned(8))) = {", v.id, len(file))
		for i, b := range file {
			if i%24 == 0 {
				o.WriteString("\n   ")
			}
			fmt.Fprintf(&o, " %d,", b)
		}
		fmt.Fprintf(&o, "\n};\n")
		fmt.Fprintf(&o, "/* bl_verdict for each query: 0 none, 1 block, 2 allow */\n")
		fmt.Fprintf(&o, "static const uint8_t blv_%s_verdict[%d] = {", v.id, len(qs))
		for i, q := range qs {
			got := blocklist.None
			if cq, ok := blocklist.Canon(q); ok {
				got = ts.Verdict(k, uint(v.bits), cq)
				if v.bits == 44 && got != meant(cq) {
					log.Fatalf("%s: hashes say %d, the entries %d", cq, got, meant(cq))
				}
			}
			count[got]++
			if i%40 == 0 {
				o.WriteString("\n   ")
			}
			fmt.Fprintf(&o, " %d,", got)
		}
		fmt.Fprintf(&o, "\n};\n/* of %d queries: %d blocked, %d allowed */\n\n", len(qs), count[blocklist.Block], count[blocklist.Allow])
	}
	precedence(&o, k)
	if err := os.WriteFile(os.Args[1], []byte(o.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}

// precedence writes a small list and queries whose verdicts are stated by hand, one per
// rule: the most specific match decides, and at one name allow beats block.
func precedence(o *strings.Builder, k blocklist.Key) {
	var es []blocklist.Entry
	add := func(kind blocklist.Kind, allow bool, s string) {
		_, err := blocklist.Parse(strings.NewReader(s), kind, func(e blocklist.Entry) {
			e.Allow = e.Allow || allow
			es = append(es, e)
		})
		if err != nil {
			log.Fatal(err)
		}
	}
	add(blocklist.Adblock, false, "||ads.com^\n||track.net^\n@@||ok.track.net^\n||deep.ok.track.net^\n")
	add(blocklist.Hosts, false, "0.0.0.0 x.site.org Both.Org.\n")
	add(blocklist.Wildcard, false, "pair.io\ndeny.site.org\n")
	add(blocklist.Domains, true, "WWW.Ads.COM.\nnowhere.example\nboth.org\npair.io\n")
	add(blocklist.Wildcard, true, "site.org\nfree.example\n")
	c := blocklist.Compile(es)
	cases := []struct {
		q    string
		want blocklist.Verdict
		why  string
	}{
		{"ads.com", blocklist.Block, "block suffix"},
		{"www.ads.com", blocklist.Allow, "allow exact beats a blocked parent suffix"},
		{"WWW.ADS.COM.", blocklist.Allow, "the same in upper case with a trailing dot"},
		{"a.www.ads.com", blocklist.Block, "allow exact covers only its name"},
		{"ok.track.net", blocklist.Allow, "allow suffix under a block suffix"},
		{"z.ok.track.net", blocklist.Allow, "its subdomains too"},
		{"deep.ok.track.net", blocklist.Block, "block suffix deeper than the allow suffix"},
		{"a.deep.ok.track.net", blocklist.Block, "and its subdomains"},
		{"site.org", blocklist.Allow, "allow suffix"},
		{"x.site.org", blocklist.Block, "block exact deeper than an allow suffix"},
		{"X.Site.Org.", blocklist.Block, "the same in mixed case with a trailing dot"},
		{"z.x.site.org", blocklist.Allow, "block exact covers only its name"},
		{"q.deny.site.org", blocklist.Block, "block suffix deeper than an allow suffix"},
		{"nowhere.example", blocklist.Allow, "allow for a name no list blocks"},
		{"x.nowhere.example", blocklist.None, "allow exact: not its subdomains"},
		{"q.free.example", blocklist.Allow, "allow suffix for names no list blocks"},
		{"both.org", blocklist.Allow, "allow exact and block exact for one name: allow"},
		{"pair.io", blocklist.Allow, "allow exact and block suffix for one name: the name is allowed"},
		{"Sub.Pair.IO.", blocklist.Block, "and its subdomains blocked"},
		{"unrelated.com", blocklist.None, "no entry"},
	}
	ts := c.Hashes(k, 44)
	file, _, err := blocklist.WriteFile(k, 44, 10, ts)
	if err != nil {
		log.Fatal(err)
	}
	meant := c.Verdict()
	fmt.Fprintf(o, "/* Precedence: a hand-made list (see precedence in blockvectors) and the verdict for each query. */\n")
	fmt.Fprintf(o, "static const uint8_t blv_prec_file[%d] __attribute__((aligned(8))) = {", len(file))
	for i, b := range file {
		if i%24 == 0 {
			o.WriteString("\n   ")
		}
		fmt.Fprintf(o, " %d,", b)
	}
	fmt.Fprintf(o, "\n};\nstatic const struct {\n    const char *q;\n    uint8_t want; /* 0 none, 1 block, 2 allow */\n} blv_prec[%d] = {\n", len(cases))
	for _, cs := range cases {
		cq, _ := blocklist.Canon(cs.q)
		if meant(cq) != cs.want || ts.Verdict(k, 44, cq) != cs.want {
			log.Fatalf("precedence %s: compiler says %d, want %d (%s)", cs.q, meant(cq), cs.want, cs.why)
		}
		fmt.Fprintf(o, "    { %q, %d }, /* %s */\n", cs.q, cs.want, cs.why)
	}
	fmt.Fprintf(o, "};\n")
}
